Make crate for axum
AzureMarker/shaku pull request #31
Opened 2021-11-22 19:30 UTC by Dispersia

Hello, I plan to use this crate with Axum, and just did all of the same logic (in axum's way) from the rocket/actix-web examples. If you prefer to not take on the burden of maintaining something that's so new and has constant new releases, I can close this PR and host it myself, just thought it might be useful for others too. Feel free to give any descriptions you would like for better error messaging :)
 
 Thanks

2021-11-25 23:22 UTC, AzureMarker requested changes
Thanks for the PR!

2021-11-25 23:22 UTC, AzureMarker commented on shaku_axum/tests/module_interface.rs
> +use shaku::{module, Component, HasComponent, HasProvider, Interface, Provider};
This should copy over the comment from the similar test in shaku_actix (modified for axum as required).

2021-11-26 00:32 UTC, Dispersia commented on shaku_axum/src/inject_provided.rs
> +/// trait HelloWorld: Interface {
Was my mistake, didn't realize provider didn't need it, but component did. However you were right, it did still need Send + Sync, so marked it accordingly. Thanks!

2021-11-26 00:34 UTC, Dispersia commented on shaku_axum/src/inject_provided.rs
> +/// trait HelloWorld: Interface {
Just curious though on this comment, you stated only when "thread_safe" feature is enabled, but I had enabled it by default on shaku (just following the actix/rocket example), is there a case a user can disable that?

2021-11-27 00:12 UTC, AzureMarker commented on shaku_axum/src/inject_provided.rs
> +                format!("{}", e),
nit: this can use `to_string`:
```suggestion
                e.to_string(),
```

2021-11-28 00:28 UTC, AzureMarker approved these changes

2021-11-28 00:29 UTC, AzureMarker commented
Thanks for the PR! I'll release the crate shortly.

2021-11-28 00:29 UTC, merged

2021-11-28 00:33 UTC, AzureMarker commented
@Dispersia can I list you in the authors array as `Aaron Housh <dispersias@gmail.com>`?

2021-11-28 02:33 UTC, Dispersia commented
Sure! You didn't have to do that, but thank you haha. This crate has been fantastic at helping my dotnet/scala friends move over to Rust, so thank you for it as well while I'm here :)

2021-11-28 22:25 UTC, AzureMarker commented
shaku_axum 0.1.0 is released: https://crates.io/crates/shaku_axum/0.1.0